import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Spotlight } from "@/components/ui/Spotlight";
import { Inter as FontSans } from "next/font/google"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div>
          <Toaster />
        </div>
        <div className="flex items-center justify-center h-screen w-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
