import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css"; 
import { Inter as FontSans } from "next/font/google";
// import Link from "next/link";
import { AuthProvider } from "@/context/AuthContext";

const inter = FontSans({ subsets: ["latin"], display: "swap"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`dark ${inter.className}`} >
      <body >
        <Toaster position="bottom-right" reverseOrder={false} />
        <div className="flex items-center justify-center h-screen w-screen bg-gray-900">
          <AuthProvider>
            {children}
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
